name: Build
on:
  push:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install remark-js
        run: npm install -g reveal-md

      - name: Build static slide deck
        run: reveal-md slides.md --static _static --static-dirs=assets
